# Generated by Django 3.2.7 on 2021-09-07 13:32

from turtle import mode
import django
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20210903_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(model_name="cartitem", name="cart"),
        migrations.RemoveField(model_name="cart", name="id"),
        migrations.RenameField(model_name="cart", old_name="temp_id", new_name="id"),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, editable=False
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.cart",
            ),
        ),
    ]
